### PR TITLE
fix: add MIME type configuration to nginx

### LINKED ISSUE #10: Cannot load CSS files
CSS files are not loaded as stylesheets and cause broken layout.

Console warning message:
```
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://api.glossm.com/static/admin/css/responsive.css".
```

### PR DESCRIPTION
**Pull request by gunwooterry**
You need to restart the nginx container and force-refresh the browser after applying this.

Resolve #10.

### CODE REVIEW

**Comment by SNUSFA** [comment]
Sees like CSS files are loaded properly, for the admin page. 
But the root page seems to be still broken. Is this fine?

**Comment by mnkykm** [comment]
Sees like CSS files are loaded properly, for the admin page.
But the root page seems to be still broken. Is this fine?

**Comment by gunwooterry** [comment]
It is not broken at all. That's because we mapped nothing to the root URL, `/`, in [`urls.py`](https://github.com/glossm/api/blob/master/django/glossm/urls.py).

**Comment by mnkykm** [comment]
Okay, then. Everything is under control!

**Review by mnkykm — APPROVED** [review]

**Pull request merged**
